version: '3.4'

services:
  worldtools.api:
    image: ${DOCKER_REGISTRY-}worldtoolsapi
    build:
      context: .
      dockerfile: WorldTools.API/Dockerfile

  worldtools.api.queries:
    image: ${DOCKER_REGISTRY-}worldtoolsapiqueries
    build:
      context: .
      dockerfile: WorldTools.API.Queries/Dockerfile

