apiVersion: v1
kind: Service
metadata:
    name: microservice-api-commands-service
    labels:
        name: microservice-api-commands-service
        app: microservice
spec:
    type: loadBalancer
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30008
    selector:
        app: microservice-api-commands
		type: microservice